# -*- coding:utf-8 -*-

from saklient.errors.httpnotfoundexception import HttpNotFoundException
from saklient.errors.httpnotfoundexception import HttpNotFoundException

# module saklient.cloud.errors.invaliduriargumentexception

class InvalidUriArgumentException(HttpNotFoundException):
    ## 対象が見つかりません。パスに使用できない文字が含まれています。
    
    # (class field) default_message = "対象が見つかりません。パスに使用できない文字が含まれています。"
    
    pass
